import React, { useState } from 'react';
import { Play, ShieldCheck, Film, Award, CheckCircle2 } from 'lucide-react';

export const VideoShowcase: React.FC = () => {
  const [isPlaying, setIsPlaying] = useState(false);
  const videoId = 'XyjkP5ENGHk';
  const embedUrl = `https://www.youtube.com/embed/${videoId}?autoplay=1&rel=0`;

  return (
    <section className="py-20 bg-[#0B0C0E] relative overflow-hidden section-gpu-optimize">
      {/* GPU-Native Ambient Gold Glow */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] rounded-full pointer-events-none glow-orb-gold" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 space-y-12">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto space-y-4">
          <div className="inline-flex items-center space-x-2 px-3.5 py-1 rounded-full glass-panel border border-[#D4AF37]/30 text-xs font-semibold uppercase tracking-widest text-[#D4AF37]">
            <Film className="w-3.5 h-3.5" />
            <span>Exclusive Architectural Film</span>
          </div>
          <h2 className="text-3xl sm:text-5xl font-serif text-white">
            Experience the Art of <span className="gold-gradient-text italic font-normal">Luxury Interiors</span>
          </h2>
          <p className="text-neutral-400 font-light text-base sm:text-lg">
            Take a guided tour through Decor8India's award-winning design process, meticulous craftsmanship, and signature turnkey residential builds.
          </p>
        </div>

        {/* Video Player Box */}
        <div className="max-w-5xl mx-auto">
          <div className="relative rounded-3xl overflow-hidden glass-card border border-white/15 p-2 sm:p-4 shadow-2xl group">
            
            {/* Outer Gold Border Glow */}
            <div className="absolute -inset-0.5 bg-gradient-to-r from-[#D4AF37]/40 via-amber-500/20 to-[#D4AF37]/40 rounded-3xl blur opacity-30 group-hover:opacity-60 transition duration-1000" />

            <div className="relative rounded-2xl overflow-hidden aspect-video bg-black/90">
              {isPlaying ? (
                <iframe 
                  src={embedUrl}
                  title="Decor8India Luxury Interiors Showcase"
                  className="w-full h-full border-0"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                  allowFullScreen
                />
              ) : (
                <div className="relative w-full h-full cursor-pointer group/thumb" onClick={() => setIsPlaying(true)}>
                  {/* YouTube HD Thumbnail */}
                  <img 
                    src={`https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`}
                    alt="Decor8India Studio Tour"
                    loading="lazy"
                    decoding="async"
                    className="w-full h-full object-cover group-hover/thumb:scale-105 transition-transform duration-700 opacity-80"
                    onError={(e) => {
                      // Fallback if maxresdefault isn't generated by YouTube yet
                      (e.target as HTMLImageElement).src = `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`;
                    }}
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/40 to-black/30 flex flex-col items-center justify-center p-6 space-y-4">
                    
                    {/* Glowing Play Button */}
                    <div className="relative">
                      <div className="absolute -inset-4 bg-[#D4AF37]/30 rounded-full blur-xl animate-pulse" />
                      <button 
                        type="button"
                        aria-label="Play Video Showcase"
                        className="relative w-20 h-20 sm:w-24 sm:h-24 rounded-full gold-gradient-bg flex items-center justify-center text-black shadow-2xl transform group-hover/thumb:scale-110 transition-transform duration-300"
                      >
                        <Play className="w-9 h-9 sm:w-10 sm:h-10 fill-current ml-1" />
                      </button>
                    </div>

                    <div className="text-center space-y-1">
                      <div className="text-lg sm:text-2xl font-serif font-bold text-white tracking-wide">
                        Watch Studio Walkthrough & Signature Tour
                      </div>
                      <div className="text-xs sm:text-sm text-[#D4AF37] font-mono font-medium">
                        Click to Play 4K Video Showcase
                      </div>
                    </div>

                  </div>
                </div>
              )}
            </div>

            {/* Bottom Highlight Badges */}
            <div className="mt-4 pt-4 px-2 sm:px-4 border-t border-white/10 flex flex-wrap items-center justify-between gap-4 text-xs text-neutral-400 font-mono">
              <div className="flex items-center space-x-2">
                <CheckCircle2 className="w-4 h-4 text-[#D4AF37]" />
                <span>Architectural Precision & German Fittings</span>
              </div>
              <div className="flex items-center space-x-2">
                <Award className="w-4 h-4 text-[#D4AF37]" />
                <span>Featured Luxury Project Walkthrough</span>
              </div>
              <div className="flex items-center space-x-2">
                <ShieldCheck className="w-4 h-4 text-[#D4AF37]" />
                <span>10-Year Turnkey Warranty</span>
              </div>
            </div>

          </div>
        </div>

      </div>
    </section>
  );
};
